version: '3.3'
services:
  bot:
    container_name: tblp_bot
    build: bot
#    image:  registry.gitlab.com/lpbt/lpbt/bot:${TAG}
    environment:
      - TOKEN=${TOKEN}
      - OWNER=${OWNER}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
#      - FRONTEND_URL_HTTPS=${FRONTEND_URL_HTTPS}
    restart: always
    networks:
      app:
        ipv4_address: 172.16.30.2

  backend:
    container_name: tblp_backend
    build: backend
#    image:  registry.gitlab.com/lpbt/lpbt/backend:${TAG}
    volumes:
      - ./dbs:/backend/dbs
#    ports:
#      - "8000:8000"
    restart: always
    networks:
      app:
        ipv4_address: 172.16.30.3

  frontend:
    container_name: tblp_frontend
    build: frontend
#    image:  registry.gitlab.com/lpbt/lpbt/frontend:${TAG}
    restart: always
    networks:
      app:
        ipv4_address: 172.16.30.4
    ports:
      - "5100:5100"

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine3.18
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/locations/:/etc/nginx/locations/
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/log/:/etc/nginx/log/
      - ./nginx/snippets/:/etc/nginx/snippets/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/proxy-params:/etc/nginx/proxy-params
      - ./nginx/access.log:/etc/nginx/access.log
      - ./nginx/error.log:/etc/nginx/error.log
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      app:
        ipv4_address: 172.16.30.5

  userbot:
    container_name: tblp_userbot
    build: userbot
    #    image:  registry.gitlab.com/lpbt/lpbt/bot:${TAG}
    environment:
      - USERTOKEN=${USERTOKEN}
      - OWNER=${OWNER}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    #      - FRONTEND_URL_HTTPS=${FRONTEND_URL_HTTPS}
    restart: always
    networks:
      app:
        ipv4_address: 172.16.30.6

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.30.0/24
